name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    
env:
  DOTNET_VERSION: '6.0.x'
  
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
        
      - name: Add SharpDX Package
        run: |
           dotnet add package SharpDX --version ${{ needs.PublishPackages.outputs.buildVersion }}
           git commit -a -m "Bump to ${{ github.event.head_commit.message }}" -m "Version <githubusername_orgname>/<nuget_package_repo_name>@${{ needs.PublishPackages.outputs.sha7 }}"
           git push
           
      - name: Add SharpDX.Desktop Package
        run: |
           dotnet add package SharpDX.Desktop --version ${{ needs.PublishPackages.outputs.buildVersion }}
           git commit -a -m "Bump to ${{ github.event.head_commit.message }}" -m "Version <githubusername_orgname>/<nuget_package_repo_name>@${{ needs.PublishPackages.outputs.sha7 }}"
           git push
           
      - name: Add SharpDX.Direct3D9 Package
        run: |
           dotnet add package SharpDX.Direct3D9 --version ${{ needs.PublishPackages.outputs.buildVersion }}
           git commit -a -m "Bump to ${{ github.event.head_commit.message }}" -m "Version <githubusername_orgname>/<nuget_package_repo_name>@${{ needs.PublishPackages.outputs.sha7 }}"
           git push
           
      - name: Add SharpDX.DirectInput Package
        run: |
           dotnet add package SharpDX.DirectInput --version ${{ needs.PublishPackages.outputs.buildVersion }}
           git commit -a -m "Bump to ${{ github.event.head_commit.message }}" -m "Version <githubusername_orgname>/<nuget_package_repo_name>@${{ needs.PublishPackages.outputs.sha7 }}"
           git push
           
      - name: Add SharpDX.DirectSound Package
        run: |
           dotnet add package SharpDX.DirectSound --version ${{ needs.PublishPackages.outputs.buildVersion }}
           git commit -a -m "Bump to ${{ github.event.head_commit.message }}" -m "Version <githubusername_orgname>/<nuget_package_repo_name>@${{ needs.PublishPackages.outputs.sha7 }}"
           git push
           
      - name: Add SharpDX.Mathematics Package
        run: |
           dotnet add package SharpDX.Mathematics --version ${{ needs.PublishPackages.outputs.buildVersion }}
           git commit -a -m "Bump to ${{ github.event.head_commit.message }}" -m "Version <githubusername_orgname>/<nuget_package_repo_name>@${{ needs.PublishPackages.outputs.sha7 }}"
           git push

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
